### ISSUE TITLE
Demo crashes

### ISSUE THREAD

**Issue by glibersat** [josephwilk/overtone.device.launchpad#12]
Hi,

First, thanks for this amazing piece of code, really what I expected from a complete library for the launchpad. I'm trying to run the examples, but as soon as I hit "down + vol" to trigger a sequence, I get this traceback:

<pre>
java.lang.ClassCastException: clojure.lang.PersistentVector cannot be cast to java.lang.Number
    at launchpad.grid$row.invoke(grid.clj:84)
    at launchpad.state_maps$row.invoke(state_maps.clj:55)
    at user$fire_sequence.invoke(form-init2779641673960982670.clj:17)
    at user$eval15225$fn__15226.invoke(form-init2779641673960982670.clj:19)
    at launchpad.device$side_event_handler$fn__13742.invoke(device.clj:227)
    at overtone.libs.handlers$run_handler.invoke(handlers.clj:135)
    at overtone.libs.handlers$run_handlers.invoke(handlers.clj:147)
    at overtone.libs.handlers$emhs_handle_async_events$fn__4631.invoke(handlers.clj:221)
    at clojure.lang.AFn.run(AFn.java:24)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
</pre>

Any idea?

Thank you,

Guillaume

**Comment by josephwilk** [comment]
Thanks for the report.

I'm not sure but I'll take a look on Friday. I don't have my launchpad with me at the moment but I suspect I'll be able to spot the bug or at-least give you some good pointers on how to fix it.
